# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: localhosted

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: build.cmd
  displayName: 'Build the code'

- script: |
  npm install
  C:\Users\staff\AppData\Roaming\npm\serverless deploy -v --stage qa --aws-profile serverless --force 
  displayName: 'Deploy to AWS Dev'
  failOnStderr: true